import type { User, Tournament, Match } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'ProGamer2025',
    email: 'progamer@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProGamer',
    role: 'organizer',
    createdAt: '2025-01-15T10:00:00Z',
    bio: 'Professional esports player and tournament organizer with 5 years of competitive experience.',
    stats: {
      tournamentsJoined: 24,
      tournamentsCreated: 8,
      wins: 18,
      losses: 6,
    },
  },
  {
    id: 'user-2',
    username: 'NightHawk',
    email: 'nighthawk@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NightHawk',
    role: 'player',
    createdAt: '2025-02-20T14:30:00Z',
    bio: 'Casual competitive player looking to improve.',
    stats: {
      tournamentsJoined: 12,
      tournamentsCreated: 0,
      wins: 7,
      losses: 5,
    },
  },
  {
    id: 'user-3',
    username: 'ShadowStrike',
    email: 'shadow@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shadow',
    role: 'player',
    createdAt: '2025-03-10T09:15:00Z',
    stats: {
      tournamentsJoined: 8,
      tournamentsCreated: 0,
      wins: 4,
      losses: 4,
    },
  },
  {
    id: 'user-4',
    username: 'TourneyMaster',
    email: 'master@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Master',
    role: 'organizer',
    createdAt: '2023-11-05T16:45:00Z',
    bio: 'Full-time tournament organizer. Creating competitive experiences since 2019.',
    stats: {
      tournamentsJoined: 5,
      tournamentsCreated: 15,
      wins: 3,
      losses: 2,
    },
  },
  {
    id: 'user-5',
    username: 'BlazeFury',
    email: 'blaze@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Blaze',
    role: 'player',
    createdAt: '2025-04-01T11:20:00Z',
    stats: {
      tournamentsJoined: 6,
      tournamentsCreated: 0,
      wins: 2,
      losses: 4,
    },
  },
  {
    id: 'user-6',
    username: 'CyberWolf',
    email: 'cyber@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cyber',
    role: 'player',
    createdAt: '2025-03-25T08:00:00Z',
    stats: {
      tournamentsJoined: 10,
      tournamentsCreated: 0,
      wins: 6,
      losses: 4,
    },
  },
  {
    id: 'user-7',
    username: 'PhoenixRise',
    email: 'phoenix@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Phoenix',
    role: 'player',
    createdAt: '2025-02-14T13:30:00Z',
    stats: {
      tournamentsJoined: 15,
      tournamentsCreated: 0,
      wins: 9,
      losses: 6,
    },
  },
  {
    id: 'user-8',
    username: 'StormBreaker',
    email: 'storm@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Storm',
    role: 'player',
    createdAt: '2025-01-28T15:45:00Z',
    stats: {
      tournamentsJoined: 20,
      tournamentsCreated: 0,
      wins: 12,
      losses: 8,
    },
  },
];

export const mockTournaments: Tournament[] = [
  {
    id: 'tournament-1',
    name: 'Winter Championship 2025',
    game: 'Valorant',
    description: 'The ultimate winter showdown. Compete against the best teams in the region for glory and prizes.',
    organizerId: 'user-1',
    organizerName: 'ProGamer2025',
    status: 'upcoming',
    format: 'single-elimination',
    platform: 'pc',
    region: 'north-america',
    maxParticipants: 16,
    currentParticipants: 12,
    prizePool: '$5,000',
    rules: '1. All matches are best of 3\n2. Standard competitive settings\n3. No tactical timeouts\n4. Players must check in 15 minutes before match\n5. Unsportsmanlike conduct results in disqualification',
    startDate: '2025-12-20T18:00:00Z',
    registrationDeadline: '2025-12-19T23:59:00Z',
    createdAt: '2025-11-01T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
    participants: ['user-2', 'user-3', 'user-5', 'user-6', 'user-7', 'user-8'],
  },
  {
    id: 'tournament-2',
    name: 'Pro League Season 5',
    game: 'League of Legends',
    description: 'Season 5 of the most prestigious amateur league. Show your skills and climb the ranks.',
    organizerId: 'user-4',
    organizerName: 'TourneyMaster',
    status: 'live',
    format: 'round-robin',
    platform: 'pc',
    region: 'europe',
    maxParticipants: 8,
    currentParticipants: 8,
    prizePool: '$2,500',
    rules: '1. Best of 1 in group stage\n2. Best of 3 in playoffs\n3. Standard tournament draft\n4. Pauses limited to 10 minutes total\n5. All communication in English',
    startDate: '2025-12-10T14:00:00Z',
    endDate: '2025-12-17T22:00:00Z',
    registrationDeadline: '2025-12-09T23:59:00Z',
    createdAt: '2025-10-20T08:30:00Z',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80',
    participants: ['user-2', 'user-3', 'user-5', 'user-6', 'user-7', 'user-8', 'user-1', 'user-4'],
  },
  {
    id: 'tournament-3',
    name: 'Street Fighter Masters',
    game: 'Street Fighter 6',
    description: 'Test your fighting game skills against competitors from around the world.',
    organizerId: 'user-1',
    organizerName: 'ProGamer2025',
    status: 'completed',
    format: 'double-elimination',
    platform: 'cross-platform',
    region: 'global',
    maxParticipants: 32,
    currentParticipants: 32,
    prizePool: '$1,000',
    rules: '1. Double elimination bracket\n2. Best of 3 until finals\n3. Grand finals best of 5\n4. Standard tournament settings\n5. Bracket reset in grand finals',
    startDate: '2025-11-15T16:00:00Z',
    endDate: '2025-11-17T20:00:00Z',
    registrationDeadline: '2025-11-14T23:59:00Z',
    createdAt: '2025-10-01T12:00:00Z',
    image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&q=80',
    participants: ['user-2', 'user-3', 'user-5', 'user-6'],
  },
  {
    id: 'tournament-4',
    name: 'Console Clash Cup',
    game: 'Call of Duty',
    description: 'The premier console FPS tournament. Battle it out on PlayStation and Xbox.',
    organizerId: 'user-4',
    organizerName: 'TourneyMaster',
    status: 'upcoming',
    format: 'single-elimination',
    platform: 'playstation',
    region: 'north-america',
    maxParticipants: 64,
    currentParticipants: 45,
    prizePool: '$3,000',
    rules: '1. Hardpoint, Search & Destroy, Control rotation\n2. CDL ruleset\n3. Best of 5 all matches\n4. GAs apply\n5. Must use tournament Discord for communication',
    startDate: '2025-12-28T15:00:00Z',
    registrationDeadline: '2025-12-27T20:00:00Z',
    createdAt: '2025-11-15T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&q=80',
    participants: ['user-2', 'user-5', 'user-7'],
  },
  {
    id: 'tournament-5',
    name: 'Rocket League Rumble',
    game: 'Rocket League',
    description: 'High-octane car soccer action. 3v3 teams compete for supremacy.',
    organizerId: 'user-1',
    organizerName: 'ProGamer2025',
    status: 'live',
    format: 'double-elimination',
    platform: 'cross-platform',
    region: 'europe',
    maxParticipants: 16,
    currentParticipants: 16,
    prizePool: '$1,500',
    rules: '1. 3v3 team format\n2. Best of 5 all rounds\n3. No mutators\n4. 5 minute matches\n5. Overtime until goal scored',
    startDate: '2025-12-14T12:00:00Z',
    endDate: '2025-12-14T22:00:00Z',
    registrationDeadline: '2025-12-13T23:59:00Z',
    createdAt: '2025-11-25T14:00:00Z',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80',
    participants: ['user-3', 'user-6', 'user-8'],
  },
  {
    id: 'tournament-6',
    name: 'Mobile Legends Championship',
    game: 'Mobile Legends',
    description: 'Southeast Asia\'s favorite MOBA tournament. Compete on mobile for big prizes.',
    organizerId: 'user-4',
    organizerName: 'TourneyMaster',
    status: 'upcoming',
    format: 'single-elimination',
    platform: 'mobile',
    region: 'asia',
    maxParticipants: 32,
    currentParticipants: 28,
    prizePool: '$2,000',
    rules: '1. 5v5 team format\n2. Best of 3 until semifinals\n3. Semifinals and finals best of 5\n4. Draft pick mode\n5. No hero restrictions',
    startDate: '2026-01-05T10:00:00Z',
    registrationDeadline: '2026-01-04T23:59:00Z',
    createdAt: '2025-12-01T07:00:00Z',
    image: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800&q=80',
    participants: ['user-2', 'user-7'],
  },
];

export const mockMatches: Match[] = [
  // Tournament 2 matches (Live - Round Robin)
  {
    id: 'match-1',
    tournamentId: 'tournament-2',
    round: 1,
    matchNumber: 1,
    participant1: { id: 'user-2', name: 'NightHawk', score: 1 },
    participant2: { id: 'user-3', name: 'ShadowStrike', score: 0 },
    winnerId: 'user-2',
    status: 'completed',
    scheduledAt: '2025-12-10T14:00:00Z',
    completedAt: '2025-12-10T14:45:00Z',
  },
  {
    id: 'match-2',
    tournamentId: 'tournament-2',
    round: 1,
    matchNumber: 2,
    participant1: { id: 'user-5', name: 'BlazeFury', score: 0 },
    participant2: { id: 'user-6', name: 'CyberWolf', score: 1 },
    winnerId: 'user-6',
    status: 'completed',
    scheduledAt: '2025-12-10T15:00:00Z',
    completedAt: '2025-12-10T15:50:00Z',
  },
  {
    id: 'match-3',
    tournamentId: 'tournament-2',
    round: 1,
    matchNumber: 3,
    participant1: { id: 'user-7', name: 'PhoenixRise', score: 2 },
    participant2: { id: 'user-8', name: 'StormBreaker', score: 1 },
    winnerId: 'user-7',
    status: 'completed',
    scheduledAt: '2025-12-10T16:00:00Z',
    completedAt: '2025-12-10T17:30:00Z',
  },
  {
    id: 'match-4',
    tournamentId: 'tournament-2',
    round: 2,
    matchNumber: 1,
    participant1: { id: 'user-2', name: 'NightHawk', score: 0 },
    participant2: { id: 'user-6', name: 'CyberWolf', score: 0 },
    status: 'live',
    scheduledAt: '2025-12-14T14:00:00Z',
  },
  {
    id: 'match-5',
    tournamentId: 'tournament-2',
    round: 2,
    matchNumber: 2,
    participant1: { id: 'user-7', name: 'PhoenixRise' },
    participant2: { id: 'user-1', name: 'ProGamer2025' },
    status: 'pending',
    scheduledAt: '2025-12-14T16:00:00Z',
  },
  // Tournament 5 matches (Live - Double Elimination)
  {
    id: 'match-6',
    tournamentId: 'tournament-5',
    round: 1,
    matchNumber: 1,
    participant1: { id: 'user-3', name: 'ShadowStrike', score: 3 },
    participant2: { id: 'user-6', name: 'CyberWolf', score: 1 },
    winnerId: 'user-3',
    status: 'completed',
    scheduledAt: '2025-12-14T12:00:00Z',
    completedAt: '2025-12-14T12:40:00Z',
  },
  {
    id: 'match-7',
    tournamentId: 'tournament-5',
    round: 1,
    matchNumber: 2,
    participant1: { id: 'user-8', name: 'StormBreaker', score: 2 },
    participant2: { id: 'user-2', name: 'NightHawk', score: 3 },
    winnerId: 'user-2',
    status: 'completed',
    scheduledAt: '2025-12-14T13:00:00Z',
    completedAt: '2025-12-14T13:55:00Z',
  },
  {
    id: 'match-8',
    tournamentId: 'tournament-5',
    round: 2,
    matchNumber: 1,
    participant1: { id: 'user-3', name: 'ShadowStrike' },
    participant2: { id: 'user-2', name: 'NightHawk' },
    status: 'pending',
    scheduledAt: '2025-12-14T15:00:00Z',
  },
  // Tournament 3 matches (Completed)
  {
    id: 'match-9',
    tournamentId: 'tournament-3',
    round: 1,
    matchNumber: 1,
    participant1: { id: 'user-2', name: 'NightHawk', score: 2 },
    participant2: { id: 'user-5', name: 'BlazeFury', score: 0 },
    winnerId: 'user-2',
    status: 'completed',
    scheduledAt: '2025-11-15T16:00:00Z',
    completedAt: '2025-11-15T16:35:00Z',
  },
  {
    id: 'match-10',
    tournamentId: 'tournament-3',
    round: 1,
    matchNumber: 2,
    participant1: { id: 'user-3', name: 'ShadowStrike', score: 2 },
    participant2: { id: 'user-6', name: 'CyberWolf', score: 1 },
    winnerId: 'user-3',
    status: 'completed',
    scheduledAt: '2025-11-15T17:00:00Z',
    completedAt: '2025-11-15T17:50:00Z',
  },
  {
    id: 'match-11',
    tournamentId: 'tournament-3',
    round: 2,
    matchNumber: 1,
    participant1: { id: 'user-2', name: 'NightHawk', score: 3 },
    participant2: { id: 'user-3', name: 'ShadowStrike', score: 2 },
    winnerId: 'user-2',
    status: 'completed',
    scheduledAt: '2025-11-17T18:00:00Z',
    completedAt: '2025-11-17T19:45:00Z',
  },
];

export const gamesList = [
  'Valorant',
  'League of Legends',
  'Street Fighter 6',
  'Call of Duty',
  'Rocket League',
  'Mobile Legends',
  'Counter-Strike 2',
  'Dota 2',
  'Fortnite',
  'Apex Legends',
  'Overwatch 2',
  'Super Smash Bros',
];

